### ISSUE TITLE
adjust font sizes for browser viewing

### ISSUE THREAD

**Issue by mckennapsean** [visdesignlab/visdesignlab.github.io#11]
what specific issues are there? Nina felt that some of the font-sizes felt odd on the website, I believe.

**Comment by mckennapsean** [comment]
I had to update references to fonts; it now displays the correct ones in most places. May be useful to have someone check it over, though.

**Comment by samquinan** [comment]
I made a pass and updated a few things. I'm happy with where things stand at this point but am more than happy to revisit this if people want
