### ISSUE TITLE
Journal Name Conventions

### ISSUE THREAD

**Issue by Dev-Lan** [visdesignlab/visdesignlab.github.io#112]
There are some inconsistencies for how journals are named. For example:

https://github.com/visdesignlab/visdesignlab.github.io/blob/main/_publications/2021_vis_loon.md?plain=1#L20
https://github.com/visdesignlab/visdesignlab.github.io/blob/main/_publications/2021_vis_gap.md?plain=1#L35
In general, I would say it was confusing for me to find the correct term to use for these types of fields. I would typically look back at what past papers put, but this isn't great when conferences change conventions (InfoVis → VIS). It can also be difficult to know what past papers are submitted to conferences vs TVCG.

Maybe more documentation at https://github.com/visdesignlab/visdesignlab.github.io/tree/main/_publications would help?

**Comment by Dev-Lan** [comment]
There are some inconsistencies for how journals are named. For example: 
- https://github.com/visdesignlab/visdesignlab.github.io/blob/main/_publications/2021_vis_loon.md?plain=1#L20
- https://github.com/visdesignlab/visdesignlab.github.io/blob/main/_publications/2021_vis_gap.md?plain=1#L35


In general, I would say it was confusing for me to find the correct term to use for these types of fields. I would typically look back at what past papers put, but this isn't great when conferences change conventions (InfoVis → VIS). It can also be difficult to know what past papers are submitted to conferences vs TVCG.

Maybe more documentation at https://github.com/visdesignlab/visdesignlab.github.io/tree/main/_publications would help?

**Comment by alexsb** [comment]
OK, here are guidelines, which I added to the readme. Long, but hopefully comprehensive and intiutive: 

# Include a shortened name for the journal or conference/proceedings. 
# Generally go for the colloquial name here, so InfoVis, VIS, EuroVis, VAST, CHI, TVCG. 
# Don't bother with publication format (CGF for EuroVis or TVCG for VIS papers).
# Don't mention organizations (IEEE, ACM), so VIS, not IEEE VIS, CHI, not ACM CHI.  
# Do include relevant qualifiers, such as "Short Papers" (VIS Short Papers) or "Posters" (VIS Posters)
# Don't include a year, or a shorthand for the year, so NOT: InfoVis'14
