### ISSUE TITLE
responsive design

### ISSUE THREAD

**Issue by mckennapsean** [visdesignlab/visdesignlab.github.io#18]
I have made 3 layouts for the website (we already had these, just they didn't do anything, now they scale resolution based on browser window size). this introduces some wonky design issues which we need to address. could use some more testing on devices before we push live.

I would say that we focus on wrapping up other changes and come back to these last. there are mainly just minor tweaks that need to be done (and some decisions, since content will "flow" differently on the page for mobile devices). shouldn't be too bad. will need to check on every page though.

**Comment by mckennapsean** [comment]
Did minor tweaks along all pages. Feel free to test with devices, but I am done working on this issue. Sam, feel free to close if you think it is good enough.

**Comment by samquinan** [comment]
We need to improve the responsiveness of the the team page, so I'm leaving this open

**Comment by alexsb** [comment]
The responsiveness looks fine to me. Closing.
