### ISSUE TITLE
Update Team Page

### ISSUE THREAD

**Issue by samquinan** [visdesignlab/visdesignlab.github.io#21]
Open issues include:
- [x] Add image to name linking
- [x] Responsive design behavior is still a bit wonky, especially with how the line of dots is rendering. We also probably want to make sure spacing is more consistent in the mobile view. 
- [x] I'm not entirely happy with how the team images behave responsively, but don't have time to look into it at the moment...

**Comment by mckennapsean** [comment]
I played with some of the responsive bits, to clean up a few of the major issues that exist, though a lot of minor ones still exist. Images are now linked via text on hover (so doesn't work on mobile unfortunately). I leave the rest for others to tackle. :-)

**Comment by mckennapsean** [comment]
Alex, Alex, Sam, & I talked about this remaining item today. It includes linking pictures to names better, and vice-versa.

For both, we will support both on-hover and on-click events attached to the pictures and each `.person-block` (which needs to be redesigned to better support these interactions effectively). I may make a separate issue about this factor if I want to clean up how the list of names is generated (e.g. to use flexbox to figure out how many dots to generate).

A click will add a hashtag (#) to the URL and "lock" a selection on screen. Going back or clicking again on the team page would "clear" this selection. A selected item highlights the name and the picture, and should ideally scroll that person into view. The only exception will be clicking on the name of the person which goes to their individual or external website page.

A hover will just highlight the name and picture, clearing when it is hovered off. If a person is out-of-view, no scrolling will occur. We could make the team header fixed to accommodate this, but we decided against doing that for now.

The highlighting of the picture could change the border-width or perhaps add some coloring around/behind the images. When I come to this, I will play around with some design ideas and post them. For the name, I imagined just doing a background highlight for the block, but some additional color may be splashed in too. It should be easy enough to do the highlighting based on a single function that adds (or removes) a classname to the necessary objects that causes the highlight.

**Comment by mckennapsean** [comment]
Got a working solution for clicking on people & images. Here is some sample output with some CSS, any thoughts?

![sample](https://user-images.githubusercontent.com/1406149/28892283-a36f6876-778a-11e7-98f7-f2e062002ec5.png)

**Comment by mckennapsean** [comment]
Got a working branch up with the clicking & hovering implemented. The CSS could probably use some love, but I may punt on that. :)

Also, redoing the team page for grid (even better responsiveness and layout) is a separate issue imo. Feel free to make one! These changes would require a significant rewrite (the page heavily uses SASS & Neat for its grid currently).

**Comment by alexsb** [comment]
Awesome, closing!
