### ISSUE TITLE
Banner layout does not work with images that are too small

### ISSUE THREAD

**Issue by mckennapsean** [visdesignlab/visdesignlab.github.io#30]
For example: 

![screenshot 3](https://cloud.githubusercontent.com/assets/1406149/23821584/2693ccaa-05f4-11e7-96a9-58a361ab5b87.png)

**Comment by samquinan** [comment]
The 'image' vs 'image_large' fields were switched in the binning paper record. Updated and confirmed the fix.

<img width="837" alt="screen shot 2017-03-11 at 1 26 15 pm" src="https://cloud.githubusercontent.com/assets/730653/23826667/5d1673bc-065e-11e7-8ead-194925184da3.png">
