### ISSUE TITLE
Thesis page is broken

### ISSUE THREAD

**Issue by alexsb** [visdesignlab/visdesignlab.github.io#31]
The advisor and the download button is floating around: 

![image](https://cloud.githubusercontent.com/assets/2039375/25158893/01b2bb10-2469-11e7-88af-574903228356.png)

Generally, this could use a little love.

**Comment by samquinan** [comment]
I never did a design for a thesis page. My guess is that the current broken view is a result of CSS from the rest of the site being re-used here without anybody having updating the CSS to handle the additional html content on thesis pages.

**Comment by mckennapsean** [comment]
If no one else tackles it first, I could take a stab after I have a dissertation to put on there too. If you have any expected or desired results, feel free to highlight them as well.

**Comment by alexsb** [comment]
I've been thinking about merging this with regular publications and using one (slightly adapted) layout for both. There are only a few special fields I guess, like thesis_type and advisors. Institution could be the publisher. 

But I'm also fine with keeping it separate.

**Comment by pgoffin** [comment]
I agree with Alex, to me it should follow a similar design/layout as a regular publication. The main block would be "Abstract", "Advisor", "Citation". In the right sidebar one image, and under "Resources" add the link to download the thesis.
@Alex: what do you mean by thesis_type? Bachelor/Master/Phd?

**Comment by alexsb** [comment]
Yes, I was referring to the differences with regards to the YAML headers of a thesis and a publication: 

```
---
layout: thesis
title: "Driving Genetics With Experimental Visualization"
key: 2012-thesis-bigelow
permalink: /thesis/2012_thesis_bigelow/
type: thesis
shortname: BS-Thesis-Bigelow
image: /assets/images/papers/2012_thesis_bigelow.png
author: bigelow
advisors: Miriah Meyer
year: May 2012
institution: University of Utah
thesis_type: Bachelor Thesis
pdf: 2012_thesis_bigelow.pdf
bibtex: 2012_thesis_bigelow.bib
---
```

**Comment by alexsb** [comment]
@mckennapsean fixed that 👍
