### ISSUE TITLE
Update References

### ISSUE THREAD

**Issue by alexsb** [visdesignlab/visdesignlab.github.io#32]
These papers are missing volume / issue / pages, or have "to appear" in the name:

 * [x] Poemage @ninaMc 
 * [x] Reflections on How Designers Design With Data @alex-r-bigelow 
 * [x] Iterating Between Tools to Create and Edit Visualizations @alex-r-bigelow 
 * [x] Evaluating the Impact of Binning 2D Scalar Fields @samquinan 
 * [x] s-CorrPlot: An Interactive Scatterplot for Exploring Correlation @mckennapsean

**Comment by samquinan** [comment]
Friendly reminder to update the paper's associated bibtex as well

**Comment by mckennapsean** [comment]
thanks so much, @ninaMc !
