### ISSUE TITLE
RhymeDesign paper is missing PDF

### ISSUE THREAD

**Issue by alexsb** [visdesignlab/visdesignlab.github.io#33]
This is linked from the website, but it's a 404
http://sci.utah.edu/~vdl/papers/2015_infovis_rhyme-design.pdf

**Comment by alexsb** [comment]
Changed the link to 2015_clfl_rhyme-design.pdf

**Comment by alexsb** [comment]
Also, bibtex is missing.

**Comment by alexsb** [comment]
I added the pdf, the bibtex is still missing.

**Comment by samquinan** [comment]
The pdf was technically on the server, but the filename was missing the hyphen in rhyme-design. 

<img width="615" alt="screen shot 2017-05-03 at 9 57 54 am" src="https://cloud.githubusercontent.com/assets/730653/25669535/06fe925e-2fe7-11e7-944a-749fc8602ee7.png">

Not sure why the 2 copies of the paper are different sizes though...

**Comment by alexsb** [comment]
I added one of them yesterday. Looks like I missed the misspelling.
