### ISSUE TITLE
Weaver Papers videos are missing

### ISSUE THREAD

**Issue by alexsb** [visdesignlab/visdesignlab.github.io#34]
![image](https://cloud.githubusercontent.com/assets/2039375/25644227/9fd77094-2f61-11e7-90d0-7b9fd6bbf890.png)

**Comment by samquinan** [comment]
The file names on the server were slightly off (e.g., 2015_infovis_weaver_video.m4v instead of the expected 2015_infovis_weaver.m4v). I updated the file names and verified that the links on the VDL page now resolve.
