### ISSUE TITLE
News feed is currently broken

### ISSUE THREAD

**Issue by mckennapsean** [visdesignlab/visdesignlab.github.io#43]
http://vdl.sci.utah.edu/feed.xml

**Comment by alexsb** [comment]
Should we just remove the link? I don't think that we have a lot of RSS followers ;).

**Comment by mckennapsean** [comment]
I was wondering why we had it.

It looks like a simple fix, since currently the template is loading the default HTML page and embedding XML, rather than just using this file on its own. I can fix this, if you like, or we could remove it. :)

**Comment by alexsb** [comment]
Either is fine. If it's simple, we could fix it. But if it's more than, say, 30 min work I'd not do it.

**Comment by mckennapsean** [comment]
It's a one-line fix I did in 3 min. Will push it later. :)
