### ISSUE TITLE
Older / broken content, should we remove?

### ISSUE THREAD

**Issue by mckennapsean** [visdesignlab/visdesignlab.github.io#46]
Trying to clean up some the site content & data in a new branch.

Some of this content here has not been updated fully or may have some old content (Caleydo or otherwise).

Please advise if there is anything we should keep @alexsb !

http://vdl.sci.utah.edu/contact/ (some is in the Footer, or on the SCI site, already, I think this is a holdover on the first copy)

http://vdl.sci.utah.edu/feed.xml (broken, Caleydo's is too, not sure how to fix offhand, never touched RSS)

In layouts, these are not used anywhere, so I would plan to remove:
  - acknowledgements
  - downloads
  - page (there is default)
  - project

In collections (`_config.yml`):
  - projects: no such collection exists
  - persons: shouldn't output anything, I think. may change name to 'people'
  - thesis: will move to pubs
  - datasets: no such collection exists
  - &  permalinks shouldn't be needed if a collection isn't output

**Comment by alexsb** [comment]
Agree on removing all of those. What do you mean by:

> permalinks shouldn't be needed if a collection isn't output

**Comment by mckennapsean** [comment]
It's just a setting in the config file, I was confused why it was there. The permalink tells Jekyll where to output stuff to. You shouldn't need it if you aren't outputting anything! Testing it now and removing these.
