### ISSUE TITLE
Image optimization and cleanup

### ISSUE THREAD

**Issue by mckennapsean** [visdesignlab/visdesignlab.github.io#48]
In our assets folder, we have team/people images, both colored and not. We don't use the colored photos. Shall we pare this down?

We could easily make all people images as black and white using a CSS3 grayscale filter (works in everything but IE), so we could keep color photos for those who have them. It seems like most people have only added the one rather than both.

Compression wise, I can add some info to the readme about this. A great site is [optimizilla](http://optimizilla.com/) since you can work in small batches and customize quality easily. I can compress what we have here if it is larger.

I plan to convert the team/people images to JPG (better compression for people), but PNGs are  recommended for most publications, I am guessing.

Also, it looks like someone added a video file into the paper images? Is there a reason for that? That would explode the repository if this was done with all the papers.

**Comment by alexsb** [comment]
Yes, let's do colored consistently and use css to grayscale. 

Videos should be hosted on the SCI webserver, like the paper sources.

**Comment by mckennapsean** [comment]
I tried doing the CSS, and I remember an issue: the filter applies to the ENTIRE element, including the border. That takes away all color... alas! This would require a more significant rewrite of the team page to implement. I tried wrapping an inline-block around it, but it broke a lot of the JS code rendering the team banner. So not as easy as I'd hope.

Also, a few people do not have color photos. And some of the color photos would require some additional tweaking to look good in grayscale (since they are too dark or too light).

The images will be preserved in the history if someone wants to implement this in the future, but for now we will require people to submit grayscale images since that is all we use.

**Comment by mckennapsean** [comment]
I added large binary files to gitignore file so hopefully that helps avoid accidental commits. I compressed all of our current images, and included updated readme instructions on how to compress images in the future. Should be good for now! Feel free to reopen or create a new issue if someone wants to tackle the colored vs grayscale headshots.
