### ISSUE TITLE
Incorrect redirect

### ISSUE THREAD

**Issue by mckennapsean** [visdesignlab/visdesignlab.github.io#52]
@alexsb - I think your redirect for UpSetR is incorrect. Should it be from `publications/2017_preprint_upsetr` instead of `preprint/2017_preprint_upsetr` ?

https://github.com/visdesignlab/visdesignlab.github.io/blob/531779e4f8bf6604700690f6f879de436f6a145f/_publications/2017_bioinformatics_upsetr.md

**Comment by mckennapsean** [comment]
All pubs by default use the `publications` prefix unless you change it in the permalink.

I can update this for you if it needs changing. Saves me a rebase. :)

**Comment by alexsb** [comment]
Yes, that's wrong. Thanks for catching that.
