### ISSUE TITLE
Missing publication possibly

### ISSUE THREAD

**Issue by mckennapsean** [visdesignlab/visdesignlab.github.io#53]
@alexsb  finished going through all the bib files. I could not find a match for one of them:

`2014_nature-methods_pov-sets`
"Points of view: Sets and intersections"

Feel free to close if you don't need it on the site, otherwise add later (preferably after the major changes I am almost done with!).

**Comment by alexsb** [comment]
This is not a peer-reviewed article. I'll have to think about that.
