### ISSUE TITLE
implement a new yaml field for publications

### ISSUE THREAD

**Issue by mckennapsean** [visdesignlab/visdesignlab.github.io#62]
Pascal wanted to put his personal publications on the website, related to #44. Is there an issue just placing them in `_publications`?

A simple solution for this request is to add a new [YAML boolean field](http://yaml.org/type/bool.html), say `personal`, which must not exist or be set falsey for a publication to appear on:
- banner of 3 pubs on home page
- recent pubs on home page
- publications list for VDL

But all publications would appear on a person's personal webpage.

**Comment by alexsb** [comment]
Yes, that's a good solution for our website and please go ahead if you prefer. 

But as I said before, it might be wise to have a personal website instead.
