### ISSUE TITLE
set line breaks in long paper titles to prevent them running the width of the screen

### ISSUE THREAD

**Issue by UtahJimmy** [visdesignlab/visdesignlab.github.io#76]
Longer paper titles (i.e. mine) feel like they run too long on the screen.  Might be to taste, though.

**Comment by alexsb** [comment]
would that be better: 
![image](https://user-images.githubusercontent.com/2039375/43987517-1e30f276-9cdf-11e8-98d2-3cee029608e3.png)


in comparison

![image](https://user-images.githubusercontent.com/2039375/43987521-2a41a4a2-9cdf-11e8-853e-fb67ea0733ea.png)

Also, for reference, when there is more content in the side-bar: 

![image](https://user-images.githubusercontent.com/2039375/43987524-46447e18-9cdf-11e8-865b-751cf9c492d5.png)

**Comment by alexsb** [comment]
I think we have a lot of papers that are just a bit too long to fit with the image, and in that case it looks good: 

![image](https://user-images.githubusercontent.com/2039375/53910952-5d467b80-4012-11e9-97cf-8d319f0e2000.png)

Breaking these cases would look awkward, hence I'd prefer to keep this as is.
