### ISSUE TITLE
Menu unusable with narrow window / mobile platform

### ISSUE THREAD

**Issue by alexsb** [visdesignlab/visdesignlab.github.io#9]
This happens: 

![image](https://cloud.githubusercontent.com/assets/2039375/12502267/e82895e2-c083-11e5-83f6-20cd6f22b2c7.png)

The original website had icons in that place. We need to put something there for small screen sizes.

**Comment by mckennapsean** [comment]
Just kept the text there, seems to work okay (going to test some responsive design for the site later).
